### ISSUE TITLE
Support for organization components?

### ISSUE THREAD

**Issue by bfovez** [markjaquith/clerk-sveltekit#31]
Hi!
Many thanks for this very useful job!
Do you plan to support the organization components as well? That is what I'd need to migrate from Auth0 to Clerk.

**Comment by markjaquith** [comment]
I can look into that! From a brief scan, it looks trivial, as these components are available via the JS SDK, so their implementation should mirror that of the existing UI components.

**Comment by bfovez** [comment]
Thank you very much!

Le ven. 24 nov. 2023 à 05:00, Mark Jaquith ***@***.***> a
écrit :
