### ISSUE TITLE
No error on invalid sign in and other component issues

### ISSUE THREAD

**Issue by LiamKrenn** [markjaquith/clerk-sveltekit#71]
**EDIT: This is an issue of #60**

1. Sign In: When a user tries to enter an email or an username, that doesn't exist in the SignIn component - no error or warning is displayed, which could lead the user to believe the site isn't working properly. `422 (Uprocessable Content)`
2. The same happens when trying to sign up with an invalid email - or the email isn't secure enough (for example Password1!) - no user feedback, just redirect. `403 (Forbidden)` followed by `422 (Unprocessable Content)`
3. Also when a user tries to reset their password, the OTP page flashes for a brief moment, and then they are redirected to login again. `422 (Unprocessable Content)` - but the reset codes still get sent

A feature to display these invalid inputs - and to fix the redirect issues would be very helpful.

**Comment by wobsoriano** [comment]
Can confirm this issue. Not sure how I missed it. This is most likely related to routing in SK.

Thanks for trying out the PR and reporting!

**Comment by wobsoriano** [comment]
Pushed an updated. Should be fixed. Thanks again!

**Comment by LiamKrenn** [comment]
Seems to be working! Thank you
